export default [
  {
    title: "TWELVE CANNETTES",
    thumbnail: "thumbnails/TWELVE CANNETTES/thumbnail.gif",
    preview: "thumbnails/TWELVE CANNETTES/preview.gif",
    association: "DOMINO CLUB",
    date: "2022 October 10",
    tagline: "NOT FOR INDIVIDUAL RESALE",
    description: "",
    links: ["https://dominoclub.itch.io/twelve-cannettes"],
  },
  {
    title: "Ten Tales from the Records of The Adamant Gambit",
    thumbnail:
      "thumbnails/Ten Tales from the Records of The Adamant Gambit/thumbnail.gif",
    preview:
      "thumbnails/Ten Tales from the Records of The Adamant Gambit/preview.gif",
    association: "#varietymegajam2021",
    date: "2022 April 16",
    tagline: "a sci-fi anthology",
    description:
      "A collaborative sci-fi anthology of 10 games made in 10 days set on the generation ship <em>The Adamant Gambit</em>.",
    links: ["https://the-adamant-gambit.itch.io/ten-tales"],
    showcase: true,
  },
  {
    title: "stairdown",
    thumbnail: "thumbnails/stairdown/thumbnail.png",
    preview: "thumbnails/stairdown/preview.png",
    association: "DOMINO CLUB",
    date: "2022 March 22",
    tagline: "a dungeon crawl dialogue",
    description: "QUEST ACCEPTED: FIND THE <strong>AMULET</strong> OF THE <strong>GOD TOH LIVE</strong><br/>Made with RenJS for DOMINO CLUB's third anonymous game jam",
    links: ["https://dominoclub.itch.io/stairdown"],
    showcase: true,
  },
  {
    title: "fib, tub, sew",
    thumbnail: "thumbnails/fib, tub, sew/thumbnail.png",
    preview: "thumbnails/fib, tub, sew/preview.png",
    association: "DOMINO CLUB",
    date: "2022 March 22",
    tagline: "not necessarily in that order",
    description:
      "yes it was me, but can you solve my riddles three<br />Made with Calico for DOMINO CLUB's third anonymous game jam",
    links: ["https://dominoclub.itch.io/fib-tub-sew"],
  },
  {
    title: "Taxi Quest 65",
    thumbnail: "thumbnails/Taxi Quest 65/thumbnail.gif",
    preview: "thumbnails/Taxi Quest 65/preview.gif",
    association: "#FFSJam",
    date: "2022 January 29",
    tagline: '"Is that REALLY necessary?"',
    description: "A sequel six years in the making to Taxi Quest 64.",
    links: [
      "https://sweetheartsquad.itch.io/taxi-quest-65",
      "https://github.com/SweetheartSquad/FFS2022-Taxi-Quest-65",
    ],
  },
  {
    title: "a decade outside",
    thumbnail: "thumbnails/a decade outside/thumbnail.gif",
    preview: "thumbnails/a decade outside/preview.gif",
    association: "Bitsy community secret santa",
    date: "2021 December 25",
    tagline: "on my sister's birthday",
    description:
      "Made for <a href='https://alyphen.itch.io'>Ren</a> as a secret santa gift.",
    links: ["https://seansleblanc.itch.io/a-decade-outside"],
  },
  {
    title: "bedside",
    thumbnail: "thumbnails/bedside/thumbnail.png",
    preview: "thumbnails/bedside/preview.png",
    association: "#BitsyJam",
    date: "2021 December 10",
    tagline: "zzz",
    description: "Made for the sleepy",
    links: ["https://seansleblanc.itch.io/bedside"],
  },
  {
    title: "We Follow The Fickle Path",
    thumbnail: "thumbnails/We Follow The Fickle Path/thumbnail.gif",
    preview: "thumbnails/We Follow The Fickle Path/preview.gif",
    association: "#GitHubGameOff",
    date: "2021 November 28",
    tagline: "A story about ants.",
    description:
      "<p>A sister is One, and one may be lost.</p><p>A sister of Many, will always have sisters.</p>",
    links: [
      "https://sweetheartsquad.itch.io/we-follow-the-fickle-path",
      "https://github.com/SweetheartSquad/GameOff2021",
    ],
    showcase: true,
  },
  {
    title: "gon't fishin",
    thumbnail: "thumbnails/gon't fishin/thumbnail.png",
    preview: "thumbnails/gon't fishin/preview.png",
    association: "#0hgame",
    date: "2021 November 07",
    tagline: "🎣",
    description: "Made in zero hours",
    links: ["https://seansleblanc.itch.io/gont-fishin"],
  },
  {
    title: "Orbital Obit.",
    thumbnail: "thumbnails/Orbital Obit/thumbnail.png",
    preview: "thumbnails/Orbital Obit/preview.png",
    association: "DOMINO CLUB",
    tagline: "",
    description:
      "<p>A Surya-class Federated orbital shuttle suffers an unknown crisis, leaving behind no survivors and too much paperwork for a couple of zoning regulators.</p><p>Made with RenJS for DOMINO CLUB's second anonymous game jam, alongside some contributions to the engine.</p>",
    date: "2021 November 02",
    links: ["https://dominoclub.itch.io/orbital-obit"],
  },
  {
    title: "wold",
    thumbnail: "thumbnails/wold/thumbnail.png",
    preview: "thumbnails/wold/preview.png",
    association: "#BitsyJam",
    date: "2021 November 01",
    description: "",
    links: ["https://seansleblanc.itch.io/wold"],
  },
  {
    title: "Advanced Bipedal Battle Armour: The Name of the Game",
    thumbnail:
      "thumbnails/Advanced Bipedal Battle Armour The Name of the Game/thumbnail.gif",
    preview:
      "thumbnails/Advanced Bipedal Battle Armour The Name of the Game/preview.gif",
    association: "#mechjam",
    date: "2021 October 05",
    tagline: "Dueling in 2.5D",
    description:
      "It all comes down to this. Friends, lovers, now rivals: Duel it out with your prized Advanced Bipedal Battle Armour to prevent a cataclysmic merger of worlds!",
    links: [
      "https://sweetheartsquad.itch.io/advanced-bipedal-battle-armour",
      "https://github.com/SweetheartSquad/MechJam",
    ],
  },
  {
    title: "Short Rest",
    thumbnail: "thumbnails/Short Rest/thumbnail.gif",
    preview: "thumbnails/Short Rest/preview.gif",
    association: "#AGBIC",
    date: "2021 September 12",
    tagline: "A party-based roguelike deckbuilder",
    description:
      "<blockquote>Somewhere outside a small village, nestled deep in the wood...<br>An immortal dragon makes its den.<br>The village calls on heroes: Noble, strong, and good...<br>But they fall again and again.</blockquote><p>A cute but deadly deckbuilding roguelike with unique spark. Carefully strategize as you make your way through the dragon's dungeon, and save the village from calamity!</p><ul><li><strong>Build and burn your deck:</strong> Every card is precious, but some things are more precious than cards...</li><li><strong>Battle your enemies:</strong> Overcome dozens of turn-based encounters and unique bosses.</li><li><strong>Bring your party to victory:</strong> Learn to use each character's strengths to make it to the next camp; if your party falls, they'll have to start again!</li></ul><blockquote>Adventures are just around the corner, so make sure your heroes are well rested...</blockquote>",
    links: [
      "https://sweetheartsquad.itch.io/short-rest",
      "https://github.com/SweetheartSquad/AGBIC2021-short-rest",
    ],
    showcase: true,
  },
  {
    title: "3pm",
    thumbnail: "thumbnails/3pm/thumbnail.png",
    preview: "thumbnails/3pm/preview.png",
    association: "",
    date: "2021 August 21",
    tagline: "get that bread",
    description: "Made for the Bipsi L(a)unch Jam",
    links: ["https://seansleblanc.itch.io/3pm"],
  },
  {
    title: "we are all but bones and dust",
    thumbnail: "thumbnails/we are all but bones and dust/thumbnail.gif",
    preview: "thumbnails/we are all but bones and dust/preview.gif",
    association: "DOMINO CLUB",
    description: "Made for DOMINO CLUB's inaugural anonymous game jam.",
    date: "2021 August 08",
    links: ["https://dominoclub.itch.io/we-are-all-but-bones-and-dust"],
    showcase: true,
  },
  {
    title: "🔍",
    thumbnail: "thumbnails/🔍/thumbnail.png",
    preview: "thumbnails/🔍/preview.png",
    association: "#BitsyJam",
    date: "2021 July 06",
    tagline: "🧑🐱",
    description: "",
    links: ["https://seansleblanc.itch.io/mag"],
  },
  {
    title: "interguylactic",
    thumbnail: "thumbnails/interguylactic/thumbnail.png",
    preview: "thumbnails/interguylactic/preview.png",
    association: "flickguy",
    date: "2021 June 24",
    tagline: "👩‍🚀",
    description: "make a guy in space!",
    links: ["https://seansleblanc.itch.io/interguylactic"],
  },
  {
    title: "taken by a guy mood",
    thumbnail: "thumbnails/taken by a guy mood/thumbnail.png",
    preview: "thumbnails/taken by a guy mood/preview.png",
    association: "flickguy",
    date: "2021 June 20",
    tagline: "dwarves galore",
    description: "make a guy who is a dwarf!",
    links: ["https://seansleblanc.itch.io/taken-by-a-guy-mood"],
  },
  {
    title: "just a cool lil guy",
    thumbnail: "thumbnails/just a cool lil guy/thumbnail.png",
    preview: "thumbnails/just a cool lil guy/preview.png",
    association: "flickguy",
    date: "2021 June 18",
    tagline: "😎",
    description: "make a cool lil guy!",
    links: ["https://seansleblanc.itch.io/just-a-cool-lil-guy"],
  },
  {
    title: "Late Fees and Damages",
    thumbnail: "thumbnails/Late Fees and Damages/thumbnail.gif",
    preview: "thumbnails/Late Fees and Damages/preview.gif",
    association: "#BitsyJam",
    date: "2021 June 14",
    tagline: "to be but a childe with a book",
    description: "Made for the overdue library books",
    links: ["https://seansleblanc.itch.io/late-fees-and-damages"],
  },
  {
    title: "ordered-dither-maker",
    thumbnail: "thumbnails/ordered-dither-maker/thumbnail.gif",
    preview: "thumbnails/ordered-dither-maker/preview.gif",
    association: "#thetooljam",
    date: "2021 May 11",
    tagline: "tool for creating ordered dither threshold textures",
    description:
      "This tool allows you to create textures that can be used as threshold maps for ordered dithering, a technique usually implemented using programmatically generated Bayer matrices.",
    links: [
      "https://seansleblanc.itch.io/ordered-dither-maker",
      "https://github.com/seleb/ordered-dither-maker",
      "https://seleb.github.io/ordered-dither-maker/",
    ],
    showcase: true,
  },
  {
    title: "Rupert Rabbit in: Murder, My Bunny",
    thumbnail: "thumbnails/Rupert Rabbit in Murder, My Bunny/thumbnail.gif",
    preview: "thumbnails/Rupert Rabbit in Murder, My Bunny/preview.gif",
    association: "#BWJam",
    date: "2021 April 25",
    tagline: "Magic, murder, and mystery in a small town bar.",
    description:
      "Marcel the Magnifical is scheduled to go on tonight, but something is amiss: explore a night of magic, murder, and mystery in a small town bar.",
    links: ["https://sweetheartsquad.itch.io/murder-my-bunny"],
  },
  {
    title: "Having the time of your life playing a bitsy game.",
    thumbnail:
      "thumbnails/Having the time of your life playing a bitsy game/thumbnail.png",
    preview:
      "thumbnails/Having the time of your life playing a bitsy game/preview.png",
    association: "#BitsyJam",
    date: "2021 March 31",
    tagline: ":D",
    description: "Made for the unfinished business",
    links: [
      "https://seansleblanc.itch.io/having-the-time-of-your-life-playing-a-bitsy-game",
    ],
  },
  {
    title: "Seal Your EP",
    thumbnail: "thumbnails/Seal Your EP/thumbnail.png",
    preview: "thumbnails/Seal Your EP/preview.png",
    association: "#EPJam7",
    date: "2021 March 21",
    tagline: "audio not meant for concentration",
    description: "",
    links: ["https://seansleblanc.itch.io/seal-your-ep"],
  },
  {
    title: "Remembering Ramayana",
    thumbnail: "thumbnails/Remembering Ramayana/thumbnail.png",
    preview: "thumbnails/Remembering Ramayana/preview.png",
    association: "",
    date: "2021 March 14",
    tagline: "an abridged and annotated epic recollection",
    description:
      "I have not read the Ramayana, but I'd like to tell it to you.",
    links: ["https://seansleblanc.itch.io/remembering-ramayana"],
  },
  {
    title: "Sunken Sailor",
    thumbnail: "thumbnails/Sunken Sailor/thumbnail.gif",
    preview: "thumbnails/Sunken Sailor/preview.gif",
    association: "#BitsyJam",
    date: "2021 February 28",
    tagline: "🌊",
    description: "Made for the seafolk",
    links: ["https://seansleblanc.itch.io/sunken-sailor"],
  },
  {
    title: "exploring a dualist foundation",
    thumbnail: "thumbnails/exploring a dualist foundation/thumbnail.png",
    preview: "thumbnails/exploring a dualist foundation/preview.png",
    association: "List Jam",
    date: "2021 February 16",
    tagline: "mumble mumble metatextual",
    description: "",
    links: ["https://seansleblanc.itch.io/exploring-a-dualist-foundation"],
  },
  {
    title: "Finder's Keplers",
    thumbnail: "thumbnails/Finder's Keplers/thumbnail.gif",
    preview: "thumbnails/Finder's Keplers/preview.gif",
    association: "#GGJ2021",
    tags: ["software", "games"],
    date: "2021 January 31",
    tagline: "Draw and guess constellations with friends",
    description:
      "This is an asynchronous multiplayer game for 2 or more players. Draw constellations using the generated prompts/starmap, and then send them to your friends and see if they can guess them all!",
    links: [
      "https://sweetheartsquad.itch.io/finders-keplers",
      "https://sweetheartsquad.github.io/ggj2021",
      "https://github.com/SweetheartSquad/ggj2021",
      "https://globalgamejam.org/2021/games/finders-keplers-5",
    ],
  },
  {
    title: "cloudfishing",
    thumbnail: "thumbnails/cloudfishing/thumbnail.gif",
    preview: "thumbnails/cloudfishing/preview.gif",
    association: "#BitsyJam",
    tags: ["software", "games", "bitsy"],
    date: "2021 January 30",
    tagline: "reel em in",
    description: "Made for the clouds",
    links: ["https://seansleblanc.itch.io/cloudfishing"],
  },
  {
    title: "sketch-to-lineart",
    thumbnail: "thumbnails/sketch-to-lineart/thumbnail.png",
    preview: "thumbnails/sketch-to-lineart/preview.png",
    association: "Personal Project",
    date: "2021 January 06",
    tagline: "tool for converting sketches to transparent lineart",
    description:
      "Simple tool to replace a common post-processing pipeline for digitizing sketches.",
    links: [
      "https://seansleblanc.itch.io/sketch-to-lineart",
      "https://github.com/seleb/sketch-to-lineart",
    ],
  },
  {
    title: "power's out",
    thumbnail: "thumbnails/power's out/thumbnail.png",
    preview: "thumbnails/power's out/preview.png",
    association: "#BitsyJam",
    date: "2021 January 04",
    tagline: "🕯",
    description: "Made for the candles",
    links: ["https://seansleblanc.itch.io/powers-out"],
  },
  {
    title: "VARIETY MEGAJAM 2020 Retrospective",
    thumbnail: "thumbnails/VARIETY MEGAJAM 2020 Retrospective/thumbnail.png",
    preview: "thumbnails/VARIETY MEGAJAM 2020 Retrospective/preview.png",
    association: "#varietymegajam2020",
    date: "2021 January 01",
    tagline: "A look back at 10 games made over 10 days.",
    description: "",
    links: [
      "https://sweetheartsquad.itch.io/variety-megajam-2020-retrospective",
    ],
  },
  {
    title: "Winter's Mane",
    thumbnail: "thumbnails/Winter's Mane/thumbnail.png",
    preview: "thumbnails/Winter's Mane/preview.png",
    association: "Bitsy community secret santa",
    date: "2021 January 01",
    tagline: "a tragedy of grand scale",
    description:
      "Made for <a href='https://ianmart1n.itch.io/'>IAN MARTIN</a> as a secret santa gift.",
    links: ["https://seansleblanc.itch.io/winters-mane"],
  },
  {
    title: "truck(r)ing REMASTERED",
    thumbnail: "thumbnails/truck(r)ing REMASTERED/thumbnail.gif",
    preview: "thumbnails/truck(r)ing REMASTERED/preview.gif",
    association: "#varietymegajam2020",
    date: "2020 December 31",
    tagline: "the truck game you know and love, but better",
    description: "",
    links: ["https://sweetheartsquad.itch.io/truckring-remastered"],
  },
  {
    title: "The Dungeoneer's Cookbook",
    thumbnail: "thumbnails/The Dungeoneer's Cookbook/thumbnail.png",
    preview: "thumbnails/The Dungeoneer's Cookbook/preview.png",
    association: "#varietymegajam2020",
    date: "2020 December 30",
    tagline: "Roasts, Bakes, and More for The Practical Adventurer",
    description: "",
    links: ["https://sweetheartsquad.itch.io/the-dungeoneers-cookbook"],
  },
  {
    title: "SUPERmarket SPY 2D",
    thumbnail: "thumbnails/SUPERmarket SPY 2D/thumbnail.gif",
    preview: "thumbnails/SUPERmarket SPY 2D/preview.gif",
    association: "#varietymegajam2020",
    date: "2020 December 29",
    tagline: "A STRATEGIC SURVEILLANCE SORTIE",
    description: "",
    links: ["https://sweetheartsquad.itch.io/supermarket-spy-2d"],
  },
  {
    title: "Le Prix d'Escalier",
    thumbnail: "thumbnails/Le Prix d'Escalier/thumbnail.png",
    preview: "thumbnails/Le Prix d'Escalier/preview.png",
    association: "#varietymegajam2020",
    date: "2020 December 28",
    tagline: '"The Price of Stairs"',
    description: "Variant of five-card draw poker.",
    links: ["https://sweetheartsquad.itch.io/le-prix-descalier"],
  },
  {
    title: "Beaks of Rage",
    thumbnail: "thumbnails/Beaks of Rage/thumbnail.gif",
    preview: "thumbnails/Beaks of Rage/preview.gif",
    association: "#varietymegajam2020",
    date: "2020 December 27",
    tagline: "An RPG beat-em-up about a regular chicken.",
    description: "",
    links: ["https://sweetheartsquad.itch.io/beaks-of-rage"],
  },
  {
    title: "Donut Get Burned!!",
    thumbnail: "thumbnails/Donut Get Burned!!/thumbnail.gif",
    preview: "thumbnails/Donut Get Burned!!/preview.gif",
    association: "#varietymegajam2020",
    date: "2020 December 26",
    tagline: "Save a donut from confectionary conundrums.",
    description: "",
    links: ["https://sweetheartsquad.itch.io/donut-get-burned"],
  },
  {
    title: "we should appreciate this little combination",
    thumbnail:
      "thumbnails/we should appreciate this little combination/thumbnail.png",
    preview:
      "thumbnails/we should appreciate this little combination/preview.png",
    association: "Bitsy community secret santa",
    date: "2020 December 25",
    tagline: "🌱",
    description:
      "Made for <a href='https://coleo_kin.itch.io/'>Emilie Reed</a> as a secret santa gift.",
    links: [
      "https://seansleblanc.itch.io/we-should-appreciate-this-little-combination",
    ],
  },
  {
    title: "Collar Me Impressed",
    thumbnail: "thumbnails/Collar Me Impressed/thumbnail.gif",
    preview: "thumbnails/Collar Me Impressed/preview.gif",
    association: "#varietymegajam2020",
    date: "2020 December 25",
    tagline: "Design an elegant cat collar with ease and speed!",
    description: "",
    links: [
      "https://sweetheartsquad.itch.io/collar-me-impressed",
      "https://github.com/SweetheartSquad/collar-me-impressed",
    ],
    showcase: true,
  },
  {
    title: "JET LI IS THE ONE (2001) ASKING YOU TO GET HIM A COFFEE",
    thumbnail:
      "thumbnails/JET LI IS THE ONE (2001) ASKING YOU TO GET HIM A COFFEE/thumbnail.png",
    preview:
      "thumbnails/JET LI IS THE ONE (2001) ASKING YOU TO GET HIM A COFFEE/preview.png",
    association: "#varietymegajam2020",
    date: "2020 December 24",
    tagline: "And he likes it strong.",
    description: "",
    links: ["https://sweetheartsquad.itch.io/jet-li-is-the-one-2001-coffee"],
  },
  {
    title: "truck(r)ing",
    thumbnail: "thumbnails/truck(r)ing/thumbnail.gif",
    preview: "thumbnails/truck(r)ing/preview.gif",
    association: "#varietymegajam2020",
    date: "2020 December 23",
    tagline: "go in a loop and collect loops",
    description: "",
    links: ["https://sweetheartsquad.itch.io/truckring"],
  },
  {
    title: "T.M.EYE",
    thumbnail: "thumbnails/T.M.EYE/thumbnail.png",
    preview: "thumbnails/T.M.EYE/preview.png",
    association: "#essayjam/#BitsyJam",
    date: "2020 November 22",
    tagline: "🔪👁",
    description: "cw: ophthalmology",
    links: ["https://seansleblanc.itch.io/tmeye"],
  },
  {
    title: "i became a goblin",
    thumbnail: "thumbnails/i became a goblin/thumbnail.png",
    preview: "thumbnails/i became a goblin/preview.png",
    association: "#Bitsyjam",
    date: "2020 November 01",
    tagline: "when i woke up this morning",
    description: "Made for the goblins",
    links: ["https://seansleblanc.itch.io/i-became-a-goblin"],
  },
  {
    title: "bred",
    thumbnail: "thumbnails/bred/thumbnail.png",
    preview: "thumbnails/bred/preview.png",
    association: "#BirthdayBitsyJam",
    date: "2020 October 24",
    tagline: "🍞",
    description:
      'Made for <a href="https://emmadaues.itch.io/">Emma Daues</a>\' birthday jam',
    links: ["https://seansleblanc.itch.io/bred"],
  },
  {
    title: "How Do You Reckon?",
    thumbnail: "thumbnails/How Do You Reckon/thumbnail.gif",
    preview: "thumbnails/How Do You Reckon/preview.gif",
    association: "#AGBIC",
    date: "2020 October 14",
    tagline: "those who wield the geometry divine know no rest",
    description:
      'Inspired by the Famicase <a href="https://famicase.com/20/softs/017.html">RECKON</a> by <a href="https://twitter.com/JonahD">Jonah Davidson</a>.',
    links: ["https://seansleblanc.itch.io/how-do-you-reckon"],
    showcase: true,
  },
  {
    title: "a chat with charon",
    thumbnail: "thumbnails/a chat with charon/thumbnail.gif",
    preview: "thumbnails/a chat with charon/preview.gif",
    association: "#BitsyJam",
    date: "2020 August 31",
    tagline: "and his endless charge",
    description: "Made for the ghost ship",
    links: ["https://seansleblanc.itch.io/a-chat-with-charon"],
  },
  {
    title: "catch and release",
    thumbnail: "thumbnails/catch and release/thumbnail.gif",
    preview: "thumbnails/catch and release/preview.gif",
    association: "#BitsyJam",
    date: "2020 July 30",
    tagline: "based on a true story",
    description: "Made for the frog",
    links: ["https://seansleblanc.itch.io/catch-and-release"],
  },
  {
    title: "hopefully good reads",
    thumbnail: "thumbnails/hopefully good reads/thumbnail.png",
    preview: "thumbnails/hopefully good reads/preview.png",
    association: "#BitsyJam",
    date: "2020 June 28",
    tagline: "browsin'",
    description: "Made for the cursed book",
    links: ["https://seansleblanc.itch.io/hopefully-good-reads"],
  },
  {
    title: "you are a skeleton",
    thumbnail: "thumbnails/you are a skeleton/thumbnail.gif",
    preview: "thumbnails/you are a skeleton/preview.gif",
    association: "#BitsyJam",
    date: "2020 May 25",
    tagline: "klik click klak",
    description: "Made for the connections",
    links: ["https://seansleblanc.itch.io/you-are-a-skeleton"],
  },
  {
    title: "Tales from the Recycle Bin",
    thumbnail: "thumbnails/Tales from the Recycle Bin/thumbnail.png",
    preview: "thumbnails/Tales from the Recycle Bin/preview.png",
    association: "#BitsyJam",
    date: "2020 May 04",
    tagline: "where ideas go to die",
    description:
      "I'm pretty good at finishing the things I start. But not everything gets finished. Made for the trash.",
    links: ["https://seansleblanc.itch.io/tales-from-the-recycle-bin"],
  },
  {
    title: "whole",
    thumbnail: "thumbnails/whole/thumbnail.png",
    preview: "thumbnails/whole/preview.png",
    association: "#BitsyJam",
    date: "2020 March 27",
    tagline: "🕳",
    description: "Made for the isolation",
    links: ["https://seansleblanc.itch.io/whole"],
  },
  {
    title: "silently screaming for six to seven hours",
    thumbnail:
      "thumbnails/silently screaming for six to seven hours/thumbnail.png",
    preview: "thumbnails/silently screaming for six to seven hours/preview.png",
    association: "#BitsyJam",
    date: "2020 March 02",
    tagline:
      ".................................................................",
    description: "Made for the silent",
    links: [
      "https://seansleblanc.itch.io/silently-screaming-for-six-to-seven-hours",
    ],
  },
  {
    title: "MYCOTERROR ]|[ UNOFFICIAL WALKTHROUGH",
    thumbnail: "thumbnails/MYCOTERROR UNOFFICIAL WALKTHROUGH/thumbnail.png",
    preview: "thumbnails/MYCOTERROR UNOFFICIAL WALKTHROUGH/preview.png",
    association: "Speculation Jam",
    date: "2020 February 18",
    tagline: "things stay the same even when they change",
    description:
      "You've been stuck on this boss for hours. Maybe you're missing something? You thought you were just too tired last night, but still lost when you tried again this morning - it just dragged it out longer. It's almost time for work, but maybe you can just branch off a guide and read it on your commute...",
    links: ["https://seansleblanc.itch.io/mycoterror-3-unofficial-walkthrough"],
  },
  {
    title: "I Can Fix It!",
    thumbnail: "thumbnails/I Can Fix It!/thumbnail.png",
    preview: "thumbnails/I Can Fix It!/preview.png",
    association: "#GGJ2020",
    date: "2020 February 02",
    tagline: "A party game about problems and solutions.",
    description:
      "A printable party game about problems and solutions inspired by games like Snake Oil and Cards Against Humanity.",
    links: [
      "https://sweetheartsquad.itch.io/i-can-fix-it",
      "https://github.com/SweetheartSquad/GGJ2020",
      "https://globalgamejam.org/2020/games/i-can-fix-5",
    ],
  },
  {
    title: "rat bastard",
    thumbnail: "thumbnails/rat bastard/thumbnail.gif",
    preview: "thumbnails/rat bastard/preview.gif",
    association: "#BitsyJam",
    date: "2020 February 02",
    tagline: "better a rat than an aristocrat",
    description: "Made for the rat",
    links: ["https://seansleblanc.itch.io/rat-bastard"],
  },
  {
    title: "rewriting our own memories, bonds, associations",
    thumbnail:
      "thumbnails/rewriting our own memories, bonds, associations/thumbnail.gif",
    preview:
      "thumbnails/rewriting our own memories, bonds, associations/preview.gif",
    association: "#Bitsmas",
    date: "2019 December 25",
    tagline: "inside out, together",
    description:
      "Made for <a href='https://empha.itch.io/'>Em</a> as a secret santa gift.",
    links: [
      "https://seansleblanc.itch.io/rewriting-our-own-memories-bonds-associations",
    ],
  },
  {
    title: "cold soup",
    thumbnail: "thumbnails/cold soup/thumbnail.png",
    preview: "thumbnails/cold soup/preview.png",
    association: "#BitsyJam",
    date: "2019 December 04",
    tagline: "🍲",
    description: "Made for the soup",
    links: ["https://seansleblanc.itch.io/cold-soup"],
  },
  {
    title: "bitsy vocal synth tester",
    thumbnail: "thumbnails/bitsy vocal synth tester/thumbnail.png",
    preview: "thumbnails/bitsy vocal synth tester/preview.png",
    association: "Personal Project",
    date: "2019 November 20",
    tagline: "tool for interactively testing the dialog audio vocal synth hack",
    description: "",
    links: ["https://seansleblanc.itch.io/bitsy-vocal-synth-tester"],
  },
  {
    title: "it's a living",
    thumbnail: "thumbnails/it's a living/thumbnail.png",
    preview: "thumbnails/it's a living/preview.png",
    association: "#BitsyJam",
    date: "2019 November 03",
    tagline: "i suppose",
    description: "Made for the ghosts with jobs ",
    links: ["https://seansleblanc.itch.io/its-a-living"],
  },
  {
    title: "taco to go",
    thumbnail: "thumbnails/taco to go/thumbnail.png",
    preview: "thumbnails/taco to go/preview.png",
    association: "#0hgame",
    date: "2019 November 03",
    tagline: "taco",
    description: "Made in zero hours",
    links: ["https://seansleblanc.itch.io/taco-to-go"],
  },
  {
    title: "houserot",
    thumbnail: "thumbnails/houserot/thumbnail.png",
    preview: "thumbnails/houserot/preview.png",
    association: "#BirthdayBitsyJam",
    date: "2019 October 20",
    tagline: "i don't leave the house much",
    description:
      'Made for <a href="https://emmadaues.itch.io/">Emma Daues</a>\' birthday jam',
    links: ["https://seansleblanc.itch.io/houserot"],
  },
  {
    title: "flue",
    thumbnail: "thumbnails/flue/thumbnail.png",
    preview: "thumbnails/flue/preview.png",
    association: "#LD45",
    date: "2019 October 06",
    tagline: "A simple game of solitaire",
    description: "",
    links: [
      "https://seansleblanc.itch.io/flue",
      "https://ldjam.com/events/ludum-dare/45/flue",
    ],
  },
  {
    title: "🐦",
    thumbnail: "thumbnails/🐦/thumbnail.png",
    preview: "thumbnails/🐦/preview.gif",
    association: "#BitsyJam",
    date: "2019 October 03",
    tagline: "*vague tweeting*",
    description: "Made for the dinosaur",
    links: ["https://seansleblanc.itch.io/bird"],
  },
  {
    title: "visual echoes",
    thumbnail: "thumbnails/visual echoes/thumbnail.gif",
    preview: "thumbnails/visual echoes/preview.gif",
    association: "#BitsyJam",
    description:
      "Talk to the cat to undo what you've done, but you can't turn back time. Made for the echo.",
    date: "2019 September 05",
    links: ["https://seansleblanc.itch.io/visual-echoes"],
  },
  {
    title: "ROUND TABLE",
    thumbnail: "thumbnails/ROUND TABLE/thumbnail.gif",
    preview: "thumbnails/ROUND TABLE/preview.gif",
    association: "#AGBIC",
    date: "2019 August 21",
    tagline: "Shoulder your burdens.",
    description:
      'The Good Queen has passed, as all must. The burden to rule falls now to The Naïve Heir, and their table of knights. Inspired by the Famicase <a href="https://famicase.com/19/softs/024.html">Round Table</a> by <a href="https://twitter.com/kump">Matt Kump</a>.',
    links: [
      "https://sweetheartsquad.itch.io/round-table",
      "https://github.com/SweetheartSquad/AGBIC2019---Round-Table",
    ],
    showcase: true,
  },
  {
    title: "stoic",
    thumbnail: "thumbnails/stoic/thumbnail.png",
    preview: "thumbnails/stoic/preview.png",
    association: "#BitsyJam",
    description: "Made for the moss",
    date: "2019 July 26",
    links: ["https://seansleblanc.itch.io/stoic"],
  },
  {
    title: "bitsy merge",
    thumbnail: "thumbnails/bitsy merge/thumbnail.png",
    preview: "thumbnails/bitsy merge/preview.png",
    association: "Personal Project",
    date: "2019 July 25",
    tagline: "merge tool for bitsy gamedata",
    description: "",
    links: [
      "https://seansleblanc.itch.io/bitsy-merge",
      "https://github.com/seleb/bitsy-merge",
    ],
  },
  {
    title: "Masks for Sale",
    thumbnail: "thumbnails/Masks for Sale/thumbnail.png",
    preview: "thumbnails/Masks for Sale/preview.png",
    association: "#BitsyJam",
    date: "2019 July 08",
    tagline: "I'm late for the masquerade!",
    description: "Made for the masks",
    links: ["https://seansleblanc.itch.io/masks-for-sale"],
  },
  {
    title: "Interview",
    thumbnail: "thumbnails/Interview/thumbnail.gif",
    preview: "thumbnails/Interview/preview.gif",
    association: "Haunted PS1 Summer Spooks",
    date: "2019 June 30",
    tagline: "They're waiting for you.",
    description: "",
    links: ["https://seansleblanc.itch.io/interview"],
  },
  {
    title: "ds_15 - fragment",
    thumbnail: "thumbnails/ds_15 - fragment/thumbnail.gif",
    preview: "thumbnails/ds_15 - fragment/preview.gif",
    association: "#FragmentJam",
    date: "2019 June 13",
    tagline: "creepy crawlies that never saw the light of day",
    description:
      'This is a tech demo from June of 2018. It is the fifteenth and last iteration of a file named "ds", after which point my inability to decide on a direction overpowered my interest in iterating further. Messy source code is available as a download for those interested, alongside GIFs of various iterations.',
    links: ["https://seansleblanc.itch.io/ds-15-fragment"],
  },
  {
    title: "I'm a cat",
    thumbnail: "thumbnails/I'm a cat/thumbnail.png",
    preview: "thumbnails/I'm a cat/preview.png",
    association: "#BitsyJam",
    date: "2019 June 06",
    tagline: "so wait you're telling me you're a cat?",
    description: "Headphones recommended",
    links: ["https://seansleblanc.itch.io/im-a-cat"],
  },
  {
    title: "Fortune's Fervour",
    thumbnail: "thumbnails/Fortune's Fervour/thumbnail.gif",
    preview: "thumbnails/Fortune's Fervour/preview.gif",
    association: "bitsy divination jam",
    date: "2019 May 15",
    tagline: "What does your future hold?",
    description:
      "Explore and learn your fate. A diviner made with artwork generated within 24h by <a href='https://twitter.com/SpritesByBitsy'>@SpritesByBitsy</a>.",
    links: ["https://sweetheartsquad.itch.io/fortunes-fervour"],
  },
  {
    title: "WHY DO BEES",
    thumbnail: "thumbnails/WHY DO BEES/thumbnail.png",
    preview: "thumbnails/WHY DO BEES/preview.png",
    association: "#BitsyJam",
    date: "2019 May 02",
    tagline: "?",
    description: "made for the bees",
    links: ["https://seansleblanc.itch.io/why-do-bees"],
  },
  {
    title: "bitsy optimizer",
    thumbnail: "thumbnails/bitsy optimizer/thumbnail.png",
    preview: "thumbnails/bitsy optimizer/preview.png",
    association: "Personal Project",
    date: "2019 April 27",
    tagline: "optimizer for bitsy gamedata",
    description: "",
    links: [
      "https://seansleblanc.itch.io/bitsy-optimizer",
      "https://github.com/seleb/bitsy-optimizer",
    ],
  },
  {
    title: "ache",
    thumbnail: "thumbnails/ache/thumbnail.png",
    preview: "thumbnails/ache/preview.png",
    association: "#BitsyJam",
    date: "2019 April 05",
    tagline: "oh!",
    description: "made for the teeth",
    links: ["https://seansleblanc.itch.io/ache"],
  },
  {
    title: "TINAR-L",
    thumbnail: "thumbnails/TINAR-L/thumbnail.gif",
    preview: "thumbnails/TINAR-L/preview.gif",
    association: "#7DRL2019",
    date: "2019 March 10",
    tagline: "This is not a rogue-like.",
    description: "An attempted rogue-like that wasn't.",
    links: ["https://seansleblanc.itch.io/tinar-l"],
  },
  {
    title: "a snail's journey",
    thumbnail: "thumbnails/a snail's journey/thumbnail.gif",
    preview: "thumbnails/a snail's journey/preview.gif",
    association: "#BitsyJam",
    tagline: "",
    description: "made for the snails",
    date: "2019 March 04",
    links: ["https://seansleblanc.itch.io/a-snails-journey"],
  },
  {
    title: "blue as the sky",
    thumbnail: "thumbnails/blue as the sky/thumbnail.png",
    preview: "thumbnails/blue as the sky/preview.png",
    association: "Personal Project",
    date: "2019 February 19",
    tagline: "#0052cc",
    description:
      "A small tech demo demonstrating a cross-engine communication layer, focused on twine and bitsy.",
    links: [
      "https://seansleblanc.itch.io/blue-as-the-sky",
      "https://github.com/seleb/bitsy-hacks/blob/master/dist/twine-bitsy-comms.js",
    ],
  },
  {
    title: "Salvage Duty",
    thumbnail: "thumbnails/Salvage Duty/thumbnail.png",
    preview: "thumbnails/Salvage Duty/preview.gif",
    association: "#BitsyJam",
    date: "2019 February 04",
    tagline: "ruins / memories",
    description:
      "Loosely based on a short playthrough of <a href='https://seaexcursion.itch.io/alone-in-the-station-remnants'>Alone in the Station Remnants</a>.",
    links: ["https://seansleblanc.itch.io/salvage-duty"],
  },
  {
    title: "Homeward Bound",
    thumbnail: "thumbnails/Homeward Bound/thumbnail.gif",
    preview: "thumbnails/Homeward Bound/preview.gif",
    association: "#GGJ2019/#1923JAM",
    date: "2019 January 28",
    tagline: "You wake up in an endless ocean...",
    description:
      "A group of seven people find themselves on a ship in the middle of an endless ocean, with no recollection of how they got there. Based on the <a href='https://www.imdb.com/title/tt0014138/'>1923 film</a> of the same name.",
    links: [
      "https://sweetheartsquad.itch.io/homeward-bound",
      "https://github.com/SweetheartSquad/GGJ2019",
      "https://globalgamejam.org/2019/games/homeward-bound-3",
    ],
  },
  {
    title: "Goodbye BURGER CITY",
    thumbnail: "thumbnails/Goodbye BURGER CITY/thumbnail.png",
    preview: "thumbnails/Goodbye BURGER CITY/preview.png",
    association: "BURGER CITY JAM",
    date: "2019 January 20",
    tagline: "city of burgers",
    description: "I never saw American Graffiti.",
    links: ["https://sweetheartsquad.itch.io/goodbye-burger-city"],
  },
  {
    title: "bitsy hacks",
    thumbnail: "thumbnails/bitsy hacks/thumbnail.gif",
    preview: "thumbnails/bitsy hacks/preview.gif",
    association: "Personal Project",
    date: "2019 January 13",
    tagline: "a collection of re-usable scripts for bitsy game maker",
    description:
      "An open source collection of re-usable scripts for <a href='https://twitter.com/adamledoux'>Adam Le Doux</a>'s <a href='https://ledoux.itch.io/bitsy'>Bitsy Game Maker</a>, adding a variety of features.",
    links: [
      "https://github.com/seleb/bitsy-hacks",
      "https://www.npmjs.com/package/@bitsy/hecks",
    ],
    showcase: true,
  },
  {
    title: "judgement",
    thumbnail: "thumbnails/judgement/thumbnail.png",
    preview: "thumbnails/judgement/preview.png",
    association: "#BitsyJam",
    date: "2018 December 30",
    tagline: "let's play tarot",
    description: "made for tarot",
    links: ["https://seansleblanc.itch.io/judgement"],
  },
  {
    title: "a holiday yarn",
    thumbnail: "thumbnails/a holiday yarn/thumbnail.png",
    preview: "thumbnails/a holiday yarn/preview.png",
    association: "Bitsy community secret santa",
    date: "2018 December 25",
    tagline: "more of a cross-stitch, really",
    description:
      "Made for <a href='https://brandonmakesthings.itch.io/'>Brandon Thread</a> as a secret santa gift.",
    links: ["https://seansleblanc.itch.io/a-holiday-yarn"],
  },
  {
    title: "Super Snow Shoveler",
    thumbnail: "thumbnails/Super Snow Shoveler/thumbnail.png",
    preview: "thumbnails/Super Snow Shoveler/preview.gif",
    association: "Pico-8 Advent Calendar",
    date: "2018 December 11",
    tagline: "~a winter classic~",
    description: "a battle between efficiency & exhaustion",
    links: [
      "https://seansleblanc.itch.io/super-snow-shoveler",
      "https://www.lexaloffle.com/bbs/?tid=32388",
    ],
  },
  {
    title: "people like when you get meta",
    thumbnail: "thumbnails/people like when you get meta/thumbnail.png",
    preview: "thumbnails/people like when you get meta/preview.png",
    association: "#LD43",
    date: "2018 December 03",
    tagline: "...right?",
    description: "a game about making games, or not",
    links: [
      "https://seansleblanc.itch.io/people-like-when-you-get-meta",
      "https://github.com/seleb/LD43",
      "https://ldjam.com/events/ludum-dare/43/people-like-when-you-get-meta",
    ],
  },
  {
    title: "ghosts aren't real",
    thumbnail: "thumbnails/ghosts aren't real/thumbnail.gif",
    preview: "thumbnails/ghosts aren't real/preview.gif",
    association: "#BitsyJam",
    tagline: "",
    date: "2018 November 24",
    description: "",
    links: ["https://seansleblanc.itch.io/ghosts-arent-real"],
  },
  {
    title: "daily",
    thumbnail: "thumbnails/daily/thumbnail.png",
    preview: "thumbnails/daily/preview.png",
    association: "#BitsyJam",
    date: "2018 November 04",
    tagline: "every day",
    description: "made for the ritual",
    links: ["https://seansleblanc.itch.io/daily"],
  },
  {
    title: "ain't no bones about it",
    thumbnail: "thumbnails/ain't no bones about it/thumbnail.png",
    preview: "thumbnails/ain't no bones about it/preview.png",
    association: "#0hgame",
    date: "2018 November 04",
    tagline: "¯\\_(ツ)_/¯",
    description: "Made in zero hours",
    links: ["https://seansleblanc.itch.io/aint-no-bones-about-it"],
  },
  {
    title: "Wolfman's Cottage Weekend",
    thumbnail: "thumbnails/Wolfman's Cottage Weekend/thumbnail.gif",
    preview: "thumbnails/Wolfman's Cottage Weekend/preview.gif",
    association: "Haunted PS1 Halloween Jam",
    date: "2018 October 31",
    tagline: "everyone needs a vacation now and then",
    description:
      "It's hard being a wolfman; everyone needs a vacation now and then. Take a load off and enjoy your cottage weekend!",
    links: [
      "https://seansleblanc.itch.io/wolfmans-cottage-weekend",
      "https://github.com/seleb/Wolfman-s-Cottage-Weekend",
    ],
  },
  {
    title: "on the hunt",
    thumbnail: "thumbnails/on the hunt/thumbnail.gif",
    preview: "thumbnails/on the hunt/preview.gif",
    association: "#twitsybotjam",
    date: "2018 October 13",
    tagline: "exploring a pastel universe the best way possible",
    description:
      "A tiny tribute to my favourite twitter bot, <a href='https://twitter.com/FermiPasteladox'>A Pastel Universe</a>.",
    links: ["https://seansleblanc.itch.io/on-the-hunt"],
  },
  {
    title: "lunar cultivation",
    thumbnail: "thumbnails/lunar cultivation/thumbnail.gif",
    preview: "thumbnails/lunar cultivation/preview.gif",
    association: "#BitsyJam",
    date: "2018 September 23",
    tagline: "oh i think i remember that game",
    description: "a half-remembrance made for the harvest",
    links: ["https://seansleblanc.itch.io/lunar-cultivation"],
  },
  {
    title: "boxboxhtml",
    thumbnail: "thumbnails/boxboxhtml/thumbnail.png",
    preview: "thumbnails/boxboxhtml/preview.gif",
    association: "Personal Project",
    date: "2018 September 19",
    tagline: "a basic WYSIWYG editor for html/css layouts",
    description:
      "A simple tool for creating html/css layouts, similar to the basics of Unity's UI editor.",
    links: [
      "https://seansleblanc.itch.io/boxboxhtml",
      "https://github.com/seleb/boxboxhtml",
    ],
  },
  {
    title: "a retrospective",
    thumbnail: "thumbnails/a retrospective/thumbnail.gif",
    preview: "thumbnails/a retrospective/preview.gif",
    association: "#BitsyJam",
    date: "2018 September 03",
    tagline: "there have been 16 bitsy jams",
    description: "an autobiographical mixtape",
    links: ["https://seansleblanc.itch.io/a-retrospective"],
  },
  {
    title: "Fontsy",
    thumbnail: "thumbnails/Fontsy/thumbnail.png",
    preview: "thumbnails/Fontsy/preview.png",
    association: "Personal Project",
    date: "2018 August 20",
    tagline: "Bitsy Font Tool",
    description:
      "With the release of Bitsy 5 came a brand-new font system. The new system is far more customizable than the old one: among other features, it includes a spec for a .bitsyfont format which can be used to make custom fonts. Since the format is plaintext, it's relatively easy to make custom fonts by typing them out in a text editor, but from a creative perspective, it's a bit hard to draw characters that way. To help with this, Fontsy provides a way to convert back-and-forth between .bitsyfont and .bitsyfont.png files, which can be used to draw fonts in a more traditional image editor.",
    links: [
      "https://seansleblanc.itch.io/fontsy",
      "https://github.com/seleb/Fontsy",
    ],
  },
  {
    title: "🔦",
    thumbnail: "thumbnails/🔦/thumbnail.gif",
    preview: "thumbnails/🔦/preview.gif",
    association: "#LOWREZJAM",
    tagline: "A raytraced lighting tech demo",
    date: "2018 August 10",
    description: "",
    links: [
      "https://seansleblanc.itch.io/torch",
      "https://github.com/seleb/LOWREZJAM2018",
      "https://seansleblanc.itch.io/torch/devlog/44317/ok-wait-but-howd-you-do-that-in-bitsy",
    ],
  },
  {
    title: "Pretty Print",
    thumbnail: "thumbnails/Pretty Print/thumbnail.gif",
    preview: "thumbnails/Pretty Print/preview.gif",
    association: "#BitsyJam",
    tagline: "",
    description: "made for the sublime",
    date: "2018 August 01",
    links: ["https://seansleblanc.itch.io/pretty-print"],
  },
  {
    title: "The Lady's Book of Decency",
    thumbnail: "thumbnails/The Lady's Book of Decency/thumbnail.png",
    preview: "thumbnails/The Lady's Book of Decency/preview.png",
    association: "#GothNovJam",
    date: "2018 July 31",
    tagline: "A Practical Treatise on Manners, Feeding, and Etiquette",
    description: "",
    links: [
      "https://seansleblanc.itch.io/the-ladys-book-of-decency",
      "https://github.com/SweetheartSquad/Gothic-Novel-Jam-2018",
    ],
  },
  {
    title: "PCM tool",
    thumbnail: "thumbnails/PCM tool/thumbnail.png",
    preview: "thumbnails/PCM tool/preview.png",
    association: "Personal Project",
    date: "2018 July 18",
    tagline: "Helper for generating generative PCM snippets",
    description:
      "Helper for generating generative PCM snippets. Output is a self-contained script which starts the audio on mousedown. Click on output to copy to clipboard.",
    links: [
      "https://seansleblanc.itch.io/pcm-tool",
      "https://github.com/seleb/PCM-tool",
    ],
  },
  {
    title: "PICO-8 fillp tool",
    thumbnail: "thumbnails/PICO-8 fillp tool/thumbnail.png",
    preview: "thumbnails/PICO-8 fillp tool/preview.gif",
    association: "Personal Project",
    date: "2018 July 09",
    tagline: "Helper for creating PICO-8 fillp patterns",
    description:
      "A little helper tool for generating fillp patterns. Output is provided as hexadecimal sum (most compact), binary sum (easiest to read), and decimal addition (verbose; matches PICO-8 example).",
    links: [
      "https://seansleblanc.itch.io/pico-8-fillp-tool",
      "https://github.com/seleb/fillp-tool",
    ],
  },
  {
    title: "There once",
    thumbnail: "thumbnails/There once/thumbnail.gif",
    preview: "thumbnails/There once/preview.gif",
    association: "#BitsyJam",
    tagline: "A branching limerick",
    description: "made for the space whales",
    date: "2018 June 30",
    links: ["https://seansleblanc.itch.io/there-once"],
  },
  {
    title: "i've never seen the ocean",
    thumbnail: "thumbnails/i've never seen the ocean/thumbnail.png",
    preview: "thumbnails/i've never seen the ocean/preview.gif",
    association: "#BitsyJam",
    tagline: "A thought",
    description: "made for the ocean",
    date: "2018 June 04",
    links: ["https://seansleblanc.itch.io/ive-never-seen-the-ocean"],
  },
  {
    title: "a night (was had) on the town",
    thumbnail: "thumbnails/a night (was had) on the town/thumbnail.png",
    preview: "thumbnails/a night (was had) on the town/preview.png",
    association: "tipsy jam",
    date: "2018 May 20",
    tagline: "now i'm home",
    description: "",
    links: ["https://seansleblanc.itch.io/a-night-was-had-on-the-town"],
  },
  {
    title: "here are my cats",
    thumbnail: "thumbnails/here are my cats/thumbnail.png",
    preview: "thumbnails/here are my cats/preview.png",
    association: "#BitsyJam",
    tagline: "",
    description: "made for the cats",
    date: "2018 April 27",
    links: ["https://seansleblanc.itch.io/here-are-my-cats"],
  },
  {
    title: "MATCH3+CONNECT4",
    thumbnail: "thumbnails/MATCH3+CONNECT4/thumbnail.gif",
    preview: "thumbnails/MATCH3+CONNECT4/preview.gif",
    association: "Ludum Dare 41",
    date: "2018 April 23",
    tagline: "harder than it sounds",
    description: "It's like match 3, but also like connect 4.",
    links: [
      "https://seansleblanc.itch.io/match3connect4",
      "https://github.com/seleb/LDJAM41",
      "https://ldjam.com/events/ludum-dare/41/match3connect4",
      "https://www.lexaloffle.com/bbs/?tid=31166",
    ],
  },
  {
    title: "This is not a Bitsy game",
    thumbnail: "thumbnails/This is not a Bitsy game/thumbnail.png",
    preview: "thumbnails/This is not a Bitsy game/preview.png",
    association: "Personal Project",
    tagline: "",
    description: "Not made with bitsy.",
    date: "2018 April 01",
    links: ["https://seansleblanc.itch.io/this-is-not-a-bitsy-game"],
  },
  {
    title: "Archeology 101",
    thumbnail: "thumbnails/Archeology 101/thumbnail.gif",
    preview: "thumbnails/Archeology 101/preview.gif",
    association: "#BitsyJam",
    date: "2018 March 28",
    tagline: "I'm late for my archeology final!",
    description: "made for the archeology",
    links: ["https://seansleblanc.itch.io/archeology-101"],
  },
  {
    title: "JOBHUNT",
    thumbnail: "thumbnails/JOBHUNT/thumbnail.png",
    preview: "thumbnails/JOBHUNT/preview.png",
    association: "Personal Project",
    date: "2018 March 28",
    tagline: "hunt for job",
    description: "",
    links: ["https://seansleblanc.itch.io/jobhunt"],
  },
  {
    title: "Definitely a Real MMO",
    thumbnail: "thumbnails/Definitely a Real MMO/thumbnail.png",
    preview: "thumbnails/Definitely a Real MMO/preview.png",
    association: "Personal Project",
    date: "2018 March 22",
    tagline: 'it\'s "fun"!',
    description: "",
    links: ["https://seansleblanc.itch.io/definitely-a-real-mmo"],
  },
  {
    title: "bitsnake",
    thumbnail: "thumbnails/bitsnake/thumbnail.gif",
    preview: "thumbnails/bitsnake/preview.gif",
    association: "Personal Project",
    date: "2018 March 21",
    tagline: "what if bitsy but also snake??",
    description: "*chomp*",
    links: ["https://seansleblanc.itch.io/bitsnake"],
  },
  {
    title: "This seems bad.",
    thumbnail: "thumbnails/This seems bad/thumbnail.png",
    preview: "thumbnails/This seems bad/preview.png",
    association: "Bitsy hack jam",
    date: "2018 March 07",
    tagline: "T-minus 1 minute to landing.",
    description: "",
    links: ["https://seansleblanc.itch.io/this-seems-bad"],
  },
  {
    title: "Tea for Two",
    thumbnail: "thumbnails/Tea for Two/thumbnail.gif",
    preview: "thumbnails/Tea for Two/preview.gif",
    association: "#BitsyJam",
    date: "2018 February 27",
    tagline: "Two for Tea",
    description: "made for the oh no",
    links: ["https://seansleblanc.itch.io/tea-for-two"],
  },
  {
    title: "Objective: cross the room.",
    thumbnail: "thumbnails/Objective cross the room/thumbnail.png",
    preview: "thumbnails/Objective cross the room/preview.gif",
    association: "Personal Project",
    date: "2018 February 21",
    tagline: 'Bitsy games can be reset with "Ctrl+r"',
    description: "Not as easy as it sounds.",
    links: ["https://seansleblanc.itch.io/objective-cross-the-room"],
  },
  {
    title: "aubergine",
    thumbnail: "thumbnails/aubergine/thumbnail.png",
    preview: "thumbnails/aubergine/preview.gif",
    association: "Bitsy Game Swap",
    tagline: "i had that <em>dream</em> again",
    description: "Made for <a href='https://twitter.com/jctwood'>jctwood</a>.",
    date: "2018 February 21",
    links: ["https://seansleblanc.itch.io/aubergine"],
  },
  {
    title: "<3 SWEETHEART SQUAD MANIFESTO <3",
    thumbnail: "thumbnails/3 SWEETHEART SQUAD MANIFESTO 3/thumbnail.png",
    preview: "thumbnails/3 SWEETHEART SQUAD MANIFESTO 3/preview.png",
    association: "#ManifestoJam",
    date: "2018 February 12",
    tagline: "the only slightly fictionalized ramblings of a game dev chat log",
    description: "",
    links: ["https://sweetheartsquad.itch.io/sweetheart-squad-manifesto"],
  },
  {
    title: "midnight",
    thumbnail: "thumbnails/midnight/thumbnail.png",
    preview: "thumbnails/midnight/preview.gif",
    association: "#BitsyJam",
    date: "2018 January 30",
    tagline: "i'm sure the wait will pay off eventually",
    description: "made for the midnight",
    links: ["https://seansleblanc.itch.io/midnight"],
  },
  {
    title: "Tuned in... to Love",
    thumbnail: "thumbnails/Tuned in... to Love/thumbnail.gif",
    preview: "thumbnails/Tuned in... to Love/preview.gif",
    association: "#GGJ2018",
    date: "2018 January 28",
    tagline:
      "Ham it up on the airwaves and chew the rag with a variety of eligible amateur enthusiasts in this automotive dating sim.",
    description: "",
    links: ["https://sweetheartsquad.itch.io/tuned-in-to-love"],
  },
  {
    title: "÷",
    thumbnail: "thumbnails/÷/thumbnail.png",
    preview: "thumbnails/÷/preview.gif",
    association: "Personal Project",
    tagline: "",
    date: "2018 January 19",
    description: "",
    links: ["https://seansleblanc.itch.io/c3b7"],
  },
  {
    title: "Tweetcarts - 2017",
    thumbnail: "thumbnails/Tweetcarts - 2017/thumbnail.gif",
    preview: "thumbnails/Tweetcarts - 2017/preview.gif",
    association: "Personal Project",
    date: "2018 January 01",
    tagline: "PICO-8 in 140 (and then later 280) characters or less",
    description:
      "A set of 124 animations, each with source code short enough to fit in a tweet.",
    links: ["https://seansleblanc.itch.io/tweetcarts-2017"],
  },
  {
    title: "the little field in the park between home and the bus stop",
    thumbnail:
      "thumbnails/the little field in the park between home and the bus stop/thumbnail.png",
    preview:
      "thumbnails/the little field in the park between home and the bus stop/preview.gif",
    association: "#BitsyJam",
    tagline: "",
    description: "made for the snow",
    date: "2017 December 30",
    links: [
      "https://seansleblanc.itch.io/the-little-field-in-the-park-between-home-and-the-bus-stop",
    ],
  },
  {
    title: "you are the coin master",
    thumbnail: "thumbnails/you are the coin master/thumbnail.gif",
    preview: "thumbnails/you are the coin master/preview.gif",
    association: "Ludum Dare 40",
    date: "2017 December 04",
    tagline: "the more you have, the worse it is",
    description:
      "Can you collect all the coins? You just have to have them, no matter the cost!",
    links: [
      "https://seansleblanc.itch.io/you-are-the-coin-master",
      "https://ldjam.com/events/ludum-dare/40/you-are-the-coin-master",
    ],
    showcase: true,
  },
  {
    title: "The Baseball Kid: New Beginnings",
    thumbnail: "thumbnails/The Baseball Kid New Beginnings/thumbnail.gif",
    preview: "thumbnails/The Baseball Kid New Beginnings/preview.gif",
    association: "#GitHubGameOff",
    date: "2017 December 01",
    tagline: "A Select-Your-Own-Plot adventure.",
    description:
      "A throwback to the CYOA novels of our youth.  Become the Baseball Kid as you explore Fenway Park.",
    links: ["https://sweetheartsquad.itch.io/the-baseball-kid"],
  },
  {
    title: "a day on the town",
    thumbnail: "thumbnails/a day on the town/thumbnail.gif",
    preview: "thumbnails/a day on the town/preview.gif",
    association: "#BitsyJam",
    date: "2017 November 28",
    tagline: "it's gonna be a good day!",
    description: "made for the bric-a-brac",
    links: ["https://seansleblanc.itch.io/a-day-on-the-town"],
  },
  {
    title: "BONZEN",
    thumbnail: "thumbnails/BONZEN/thumbnail.png",
    preview: "thumbnails/BONZEN/preview.gif",
    association: "#selfcarejam 2",
    date: "2017 November 07",
    tagline: "Shape a sense of zen.",
    description:
      "Nothing grows in space, at least not with some help. Join an old man in his quest to bring back beautiful greenery that once covered his lost planet. Take a step back from space drama and a step into his biodome to cultivate tiny bonsai trees and find some inner peace.",
    links: ["https://sweetheartsquad.itch.io/bonzen"],
  },
  {
    title: "Song of the Space Wyrm",
    thumbnail: "thumbnails/Song of the Space Wyrm/thumbnail.gif",
    preview: "thumbnails/Song of the Space Wyrm/preview.gif",
    association: "#0hgame",
    date: "2017 November 05",
    tagline: "singing in space",
    description: "Made in zero hours",
    links: ["https://seansleblanc.itch.io/song-of-the-space-wyrm"],
  },
  {
    title: "castles",
    thumbnail: "thumbnails/castles/thumbnail.gif",
    preview: "thumbnails/castles/preview.gif",
    association: "#BitsyJam",
    date: "2017 November 01",
    tagline: "ruins",
    description: "",
    links: ["https://seansleblanc.itch.io/castles"],
  },
  {
    title: "(Unity) Better Minimal WebGL Template",
    thumbnail: "thumbnails/(Unity) Better Minimal WebGL Template/thumbnail.png",
    preview: "thumbnails/(Unity) Better Minimal WebGL Template/preview.png",
    association: "Personal Project",
    date: "2017 October 26",
    tagline: "The package is quite simple.™",
    description: "",
    links: [
      "https://seansleblanc.itch.io/better-minimal-webgl-template",
      "https://github.com/seleb/Better-Minimal-WebGL-Template",
    ],
  },
  {
    title: "running late",
    thumbnail: "thumbnails/running late/thumbnail.gif",
    preview: "thumbnails/running late/preview.gif",
    association: "#BitsyJam",
    tagline: "I'm running late!",
    description: "made for the traintracks",
    date: "2017 October 02",
    links: ["https://seansleblanc.itch.io/running-late"],
  },
  {
    title: "Rōshigumi",
    thumbnail: "thumbnails/Rōshigumi/thumbnail.gif",
    preview: "thumbnails/Rōshigumi/preview.gif",
    association: "#AGBIC",
    date: "2017 September 26",
    tagline: "A traitor threatens the Shogun in this tense shoot-em-up.",
    description:
      "You are a ronin, hired by the Rōshigumi to protect the Shogun on his visit to Kyoto. The only problem is, there's a traitor in your midst. Cut down <strike>enemies, find</strike> the <strike>traitor, and keep the</strike> Shogun <strike>safe</strike>.",
    links: [
      "https://sweetheartsquad.itch.io/roshigumi",
      "https://github.com/SweetheartSquad/AGBIC2017-Roshigumi",
      "http://network.winnitron.com/games/roshigumi",
    ],
  },
  {
    title: "|| I-,`'-' \\=I 'I '--I -' |",
    association: "#BitsyJam",
    thumbnail: "thumbnails/I-,`'-' =I    'I    '--I -'/thumbnail.gif",
    preview: "thumbnails/I-,`'-' =I    'I    '--I -'/preview.gif",
    date: "2017 August 31",
    tagline: "They've got a secret!",
    description: "made for a secret",
    links: ["https://seansleblanc.itch.io/theyve-got-a-secret"],
  },
  {
    title: "SEPULCHRE",
    thumbnail: "thumbnails/SEPULCHRE/thumbnail.gif",
    preview: "thumbnails/SEPULCHRE/preview.gif",
    association: "#LOWREZJAM",
    date: "2017 August 16",
    tagline: "It was alive once.",
    description: "",
    links: ["https://seansleblanc.itch.io/sepulchre"],
  },
  {
    title: "-A MOTH STORY-",
    thumbnail: "thumbnails/-A MOTH STORY-/thumbnail.png",
    preview: "thumbnails/-A MOTH STORY-/preview.gif",
    association: "#BitsyJam",
    date: "2017 July 29",
    tagline: "well, it's more moth-adjacent",
    description: "made for the moth",
    links: ["https://seansleblanc.itch.io/a-moth-story"],
  },
  {
    title: "I wonder...",
    thumbnail: "thumbnails/I wonder/thumbnail.gif",
    preview: "thumbnails/I wonder/preview.gif",
    association: "#BitsyJam",
    date: "2017 July 07",
    tagline: "I wonder when the next bus comes by...",
    description: "made for the daydream",
    links: ["https://seansleblanc.itch.io/i-wonder"],
  },
  {
    title: "Planet Upcycle",
    thumbnail: "thumbnails/Planet Upcycle/thumbnail.gif",
    preview: "thumbnails/Planet Upcycle/preview.gif",
    association: "OJAM",
    date: "2017 June 26",
    tagline: "What's done cannot be undone",
    description:
      "Humanity has sucked earth dry of all it's natural resources and funneled it all into the space exploring program. The only problem is how expensive space exploration is...",
    links: ["https://andybro.itch.io/planet-upcycle"],
  },
  {
    title: "walk the dog",
    thumbnail: "thumbnails/walk the dog/thumbnail.gif",
    preview: "thumbnails/walk the dog/preview.gif",
    association: "Personal Project",
    date: "2017 June 23",
    tagline: "get those walkies",
    description: "",
    links: ["https://seansleblanc.itch.io/walk-the-dog"],
  },
  {
    title: "A Visitor on Venus",
    thumbnail: "thumbnails/A Visitor On Venus/thumbnail.png",
    preview: "thumbnails/A Visitor On Venus/preview.gif",
    association: "#CGAJAM",
    date: "2017 June 14",
    tagline: "A low-rez FMV visual novel about a vacation gone wrong.",
    description:
      "On your way to Charon for a well-deserved vacation, your ship crash-lands on Venus -- a planet owned entirely by an eccentric quadrillionaire. Explore his lavish estate and find parts to repair your ship.",
    links: [
      "https://sweetheartsquad.itch.io/a-visitor-on-venus",
      "https://github.com/SweetheartSquad/CGAJAM",
    ],
  },
  {
    title: "rain",
    thumbnail: "thumbnails/rain/thumbnail.gif",
    preview: "thumbnails/rain/preview.gif",
    association: "#BitsyJam",
    date: "2017 May 30",
    tagline: "looks a bit damp out today",
    description: "made for the radio silence",
    links: ["https://seansleblanc.itch.io/rain"],
  },
  {
    title: "Plug Your EP",
    thumbnail: "thumbnails/Plug Your EP/thumbnail.png",
    preview: "thumbnails/Plug Your EP/preview.png",
    association: "#EPJam6",
    date: "2017 May 14",
    tagline: "audio not meant for aural consumption",
    description: "",
    links: [
      "https://seansleblanc.itch.io/plug-your-ep",
      "https://soundcloud.com/seansleblanc/sets/plug-your-ep",
    ],
  },
  {
    title: "let's get breakfast",
    thumbnail: "thumbnails/let's get breakfast/thumbnail.png",
    preview: "thumbnails/let's get breakfast/preview.gif",
    association: "#BitsyJam",
    tags: ["software", "games", "bitsy"],
    date: "2017 April 30",
    tagline: "you pick the place",
    description: "A short adventure game about breakfast.",
    links: ["https://seansleblanc.itch.io/lets-get-breakfast"],
  },
  {
    title: "AS Mall World",
    thumbnail: "thumbnails/AS Mall World/thumbnail.png",
    preview: "thumbnails/AS Mall World/preview.gif",
    association: "Ludum Dare 38",
    tags: ["software", "games", "Unity"],
    date: "2017 April 25",
    tagline: "Ancient Secrets: Mall World",
    description:
      "Journey through Mall World, purchase powerful artifacts, and maybe even solve the mystery of true love.",
    links: ["https://sweetheartsquad.itch.io/as-mall-world"],
  },
  {
    title: "you can do this",
    thumbnail: "thumbnails/you can do this/thumbnail.png",
    preview: "thumbnails/you can do this/preview.gif",
    association: "Personal Project",
    tags: ["software", "games", "bitsy"],
    date: "2017 April 16",
    tagline: "probably",
    description: "A short adventure game about a night out.",
    links: [
      "https://seansleblanc.itch.io/you-can-do-this",
      "https://github.com/seleb/you-can-do-this",
    ],
  },
  {
    title: "sarah goes to her friend's house",
    thumbnail: "thumbnails/sarah goes to her friend's house/thumbnail.gif",
    preview: "thumbnails/sarah goes to her friend's house/preview.gif",
    association: "#paintjam",
    tags: ["software", "games", "PixiJS"],
    date: "2017 March 20",
    tagline: "and meets some people along the way",
    description:
      "A short adventure game with artwork made exclusively in MS Paint.",
    links: [
      "https://seansleblanc.itch.io/sarah-goes-to-her-friends-house",
      "https://github.com/seleb/paintjam",
    ],
  },
  {
    title: "Duck Duck Plays the Blues",
    thumbnail: "thumbnails/Duck Duck Plays the Blues/thumbnail.png",
    preview: "thumbnails/Duck Duck Plays the Blues/preview.gif",
    association: "Personal Project",
    tags: ["software", "music", "PICO-8"],
    date: "2017 March 05",
    tagline: "Play the blues like a duck!",
    description:
      "It's been a long day, and Duck Duck's ready to unwind in the best way they know how: an impromptu jam session! Can you help them get in the groove?<br />I mean... it's not really your responsibility. I'm sure they'll be fine on their own. Why don't you just take some time to riff off the backing track and enjoy yourself? And hey, if you happened to make some smooth tunes along the way, that's cool too.",
    links: ["https://seansleblanc.itch.io/duck-duck-plays-the-blues"],
    showcase: true,
  },
  {
    title: "holt",
    thumbnail: "thumbnails/holt/thumbnail.png",
    preview: "thumbnails/holt/preview.gif",
    association: "#utopiajam",
    tags: ["software", "games", "bitsy"],
    date: "2017 February 23",
    tagline: "a bitsy utopia adventure",
    description: "A short adventure game made with Bitsy for Utopia Jam.",
    links: ["https://seansleblanc.itch.io/holt"],
  },
  {
    title: "it was a weird year",
    thumbnail: "thumbnails/it was a weird year/thumbnail.gif",
    preview: "thumbnails/it was a weird year/preview.gif",
    association: "FLATGAME Annual 2016",
    date: "2017 January 27",
    tagline: "a thing that happened in 2016",
    description: "",
    links: ["https://seansleblanc.itch.io/it-was-a-weird-year"],
  },
  {
    title: "BEAN",
    thumbnail: "thumbnails/BEAN/thumbnail.png",
    preview: "thumbnails/BEAN/preview.png",
    association: "#GGJ2017",
    date: "2017 January 22",
    tagline:
      "It's a regular old swimming race -- but if you finish with the bean, you lose!",
    description: "",
    links: ["https://sweetheartsquad.itch.io/bean"],
  },
  {
    title: "Cover Your EP",
    thumbnail: "thumbnails/Cover Your EP/thumbnail.png",
    preview: "thumbnails/Cover Your EP/preview.gif",
    association: "#EPJam5",
    tags: ["software", "music"],
    date: "2017 January 16",
    tagline: "audio not meant for listening",
    description:
      "A generative audio EP made using a variety of different techniques.",
    links: [
      "https://seansleblanc.itch.io/cover-your-ep",
      "https://soundcloud.com/seansleblanc/sets/cover-your-ep",
    ],
  },
  {
    title: "Tweetcarts - 2016",
    thumbnail: "thumbnails/Tweetcarts - 2016/thumbnail.gif",
    preview: "thumbnails/Tweetcarts - 2016/preview.gif",
    association: "#tweetjam",
    tags: ["software", "PICO-8"],
    date: "2017 January 01",
    tagline: "PICO-8 in 140 characters or less",
    description:
      "A set of 50 animations, each with source code short enough to fit in a tweet.",
    links: ["https://seansleblanc.itch.io/tweetcarts-2016"],
  },
  {
    title: "gui-butler",
    thumbnail: "thumbnails/gui-butler/thumbnail.png",
    preview: "thumbnails/gui-butler/preview.png",
    association: "Personal Project",
    tags: ["software", "tool"],
    date: "2016 December 29",
    tagline: "an itch.io butler wrapper for lazybones like me",
    description:
      "A GUI wrapper for the butler CLI which provides access to some of the features not yet available in the official itch app or web interface.",
    links: [
      "https://seansleblanc.itch.io/gui-butler",
      "https://github.com/seleb/gui-butler",
    ],
  },
  {
    title: "Bouncing Balls with the Boing Boing Boys",
    thumbnail:
      "thumbnails/Bouncing Balls with the Boing Boing Boys/thumbnail.gif",
    preview: "thumbnails/Bouncing Balls with the Boing Boing Boys/preview.gif",
    association: "Ludum Dare 37",
    tags: ["software", "games", "PixiJS"],
    date: "2016 December 13",
    tagline: "Bouncy Battles for 2-4 Buddies",
    description: "Chaotic local multiplayer deathmatch for 2-4 players.",
    links: [
      "https://sweetheartsquad.itch.io/bouncing-balls-with-the-boing-boing-boys",
      "https://github.com/sweetheartsquad/LDJAM37",
      "http://ludumdare.com/compo/ludum-dare-37/?action=preview&uid=50235",
    ],
  },
  {
    title: "STAIRS",
    thumbnail: "thumbnails/STAIRS/thumbnail.png",
    preview: "thumbnails/STAIRS/preview.gif",
    association: "Personal Project",
    tagline: "&#9776;&#9777;&#9779;&#9783;",
    tags: ["software", "PICO-8"],
    description: "A fantastic trilogy of PICO-8 falling hazards.",
    links: [
      "https://seansleblanc.itch.io/stairs",
      "https://seansleblanc.itch.io/stairs2",
      "https://seansleblanc.itch.io/stairs3",
    ],
  },
  {
    title: "NaBoMaMo2016",
    thumbnail: "thumbnails/NaBoMaMo2016/thumbnail.png",
    preview: "thumbnails/NaBoMaMo2016/preview.gif",
    association: "#NaBoMaMo",
    tags: ["software"],
    date: "2016 December 04",
    tagline: "Some bots I made.",
    description:
      "A set of six bots written during a 30-day bot-making challenge, primarily made with cheapbotsdonequick.com.",
    links: [
      "http://blog.seans.site/post/153916226291/nabomamo-2016-wrap-up",
      "https://twitter.com/SeanSLeBlanc/lists/my-bots",
      "https://github.com/seleb/NaBoMaMo2016",
    ],
  },
  {
    title: "commute",
    thumbnail: "thumbnails/commute/thumbnail.png",
    preview: "thumbnails/commute/preview.gif",
    association: "#YOUjam",
    tags: ["software", "games", "PICO-8"],
    date: "2016 November 16",
    tagline: "try to get some rest | don't miss your stop",
    description: "A tiny autobiography made in PICO-8.",
    links: [
      "https://seansleblanc.itch.io/commute",
      "https://github.com/seleb/YOUjam2016",
    ],
  },
  {
    title: "server.hack()",
    thumbnail: "thumbnails/server.hack()/thumbnail.jpg",
    preview: "thumbnails/server.hack()/preview.gif",
    association: "#procjam/game-off-2016",
    date: "2016 November 13",
    tagline: "a single-page cyberpunk board game for 2-4 players",
    description:
      "A single-page cyberpunk print-and-play board game for 2-4 players.",
    links: [
      "https://sweetheartsquad.itch.io/server-hack",
      "https://github.com/SweetheartSquad/game-off-2016",
    ],
  },
  {
    title: "Tackle Tourney TURBO",
    thumbnail: "thumbnails/Tackle Tourney TURBO/thumbnail.gif",
    preview: "thumbnails/Tackle Tourney TURBO/preview.gif",
    association: "#FishingJam 2",
    tags: ["software", "games", "PixiJS"],
    date: "2016 October 30",
    tagline: "Fishing Free-For-All For 2-4 Players",
    description:
      "Local multiplayer game for 2-4 players with plenty of fake physics.",
    links: [
      "https://seansleblanc.itch.io/tackle-tourney-turbo",
      "https://github.com/seleb/FishingJam2016",
    ],
  },
  {
    title: "listen to my game idea",
    thumbnail: "thumbnails/listen to my game idea/thumbnail.gif",
    preview: "thumbnails/listen to my game idea/preview.gif",
    association: "#gameideajam",
    tags: ["software", "PICO-8"],
    date: "2016 October 16",
    tagline: "it's gonna be great",
    description: "PICO-8 elevator pitches of the worst variety.",
    links: [
      "https://seansleblanc.itch.io/listen-to-my-game-idea",
      "http://lexaloffle.com/bbs/?tid=27909",
    ],
  },
  {
    title: "push the button to win!",
    thumbnail: "thumbnails/push the button to win!/thumbnail.gif",
    preview: "thumbnails/push the button to win!/preview.gif",
    association: "#gameideajam",
    tags: ["software", "games", "PixiJS"],
    date: "2016 October 15",
    tagline: "it's easy",
    description: "A push the button to win game.",
    links: [
      "https://seansleblanc.itch.io/push-the-button-to-win",
      "https://github.com/seleb/GAMEIDEAJAM2016",
    ],
  },
  {
    title: "Rumble Road",
    thumbnail: "thumbnails/Rumble Road/thumbnail.png",
    preview: "thumbnails/Rumble Road/preview.gif",
    association: "#GBJAM 5",
    tags: ["software", "games", "PixiJS"],
    date: "2016 October 10",
    tagline: "Turn-based GameBoy Combat",
    description: "A short adventure inspired by JRPG classics.",
    links: [
      "https://seansleblanc.itch.io/rumble-road",
      "https://github.com/seleb/GBJAM2016",
    ],
  },
  {
    title: "Duck Duck on the Loose",
    thumbnail: "thumbnails/Duck Duck on the Loose/thumbnail.gif",
    preview: "thumbnails/Duck Duck on the Loose/preview.gif",
    association: "Personal Project",
    tags: ["software", "games", "PICO-8"],
    date: "2016 September 21",
    tagline: "Look, walk, and talk like a duck!",
    description:
      "Uh oh, a flock of ducklings has gone missing, and it's up to Duck Duck to save the day! Can you help them find all seven? A pseudo-3D open-world game made with PICO-8.",
    links: [
      "https://seansleblanc.itch.io/duck-duck-on-the-loose",
      "https://github.com/seleb/DuckDuckOnTheLoose",
      "http://lexaloffle.com/bbs/?tid=27702",
    ],
  },
  {
    title: "STARSHIP",
    thumbnail: "thumbnails/STARSHIP/thumbnail.gif",
    preview: "thumbnails/STARSHIP/preview.gif",
    association: "Carleton University",
    tags: ["software", "games"],
    date: "2016 September 12",
    tagline: "A game about picking up stars with a spaceship!",
    description: "A simple game made in Processing.",
    links: [
      "https://seansleblanc.itch.io/starship",
      "https://github.com/seleb/STARSHIP",
    ],
  },
  {
    title: "In Transit",
    thumbnail: "thumbnails/In Transit/thumbnail.gif",
    preview: "thumbnails/In Transit/preview.gif",
    association: "#fermijam",
    tags: ["software", "games", "PixiJS"],
    date: "2016 September 09",
    tagline: "Relax and watch a probe search for life.",
    description: "Not really a game, but relaxing to watch.",
    links: [
      "https://seansleblanc.itch.io/in-transit",
      "https://github.com/seleb/FermiJam2016",
    ],
  },
  {
    title: "DYSCOVR",
    thumbnail: "thumbnails/DYSCOVR/thumbnail.gif",
    preview: "thumbnails/DYSCOVR/preview.gif",
    association: "Ludum Dare 36",
    tags: ["software", "games", "PixiJS"],
    date: "2016 August 30",
    tagline: "the open source platform for intergalactic archaeology",
    description:
      "An asynchronous online multiplayer sandbox about describing ancient alien technology.",
    links: [
      "https://sweetheartsquad.itch.io/DYSCOVR",
      "https://github.com/seleb/LudumDare36",
      "http://ludumdare.com/compo/ludum-dare-36/?action=preview&uid=50235",
    ],
  },
  {
    title: "One Button Duel",
    thumbnail: "thumbnails/One Button Duel/thumbnail.gif",
    preview: "thumbnails/One Button Duel/preview.gif",
    association: "#OneButtonJam",
    tagline: "A one button dueling game.",
    tags: ["software", "games", "PICO-8"],
    description:
      "This is a simple dueling game made with PICO-8. A basic peer-to-peer multiplayer mode is included through Peerjs.",
    links: [
      "https://seansleblanc.itch.io/one-button-duel",
      "https://github.com/seleb/OneButtonJam2016",
      "https://lexaloffle.com/bbs/?tid=4047",
    ],
    date: "2016 August 10",
  },
  {
    title: "STRUNG OUT in heaven's high",
    thumbnail: "thumbnails/STRUNG OUT in heaven's high/thumbnail.png",
    preview: "thumbnails/STRUNG OUT in heaven's high/preview.gif",
    association: "#agbic",
    date: "2016 July 28",
    tagline: "hitting an all-time low",
    description:
      "Do you remember a cat that's been in such an early game? We know that the cat was sent to space. Connected, monitorized, trapped in a tin can. A cat sent to die for the sake of science. High on catnip his brain envisioned adventures of space discovery, <strike>intergalactic battles, heroes and glory</strike>. But this is the final chapter of the Star Cats saga and the addiction to catnip is now out of control. Strung-out on heaven's high - hitting an all-time low - <strike>the little green wheels are following him</strike>.",
    links: [
      "https://sweetheartsquad.itch.io/strung-out-in-heavens-high",
      "https://github.com/ianmart1n/AGBIC2016",
    ],
  },
  {
    title: "P8T",
    thumbnail: "thumbnails/P8T/thumbnail.gif",
    preview: "thumbnails/P8T/preview.gif",
    association: "Personal Project",
    tags: ["software", "tool", "PICO-8"],
    date: "2016 July 23",
    tagline: "A PICO-8 Twitter Client",
    description:
      "A simple Twitter client made with PICO-8. This is a proof-of-concept meant to demonstrate netcode capabilities over GPIO.",
    links: [
      "https://seansleblanc.itch.io/p8t",
      "https://github.com/seleb/pico-8-gpio",
      "/stuff/P8T",
    ],
  },
  {
    title: "PICO-8 Styler",
    thumbnail: "thumbnails/PICO-8 Styler/thumbnail.gif",
    preview: "thumbnails/PICO-8 Styler/preview.gif",
    association: "Personal Project",
    tags: ["software", "tool"],
    date: "2016 July 14",
    tagline: "Pretty PICO-8 Pages!",
    description:
      "A PHP tool for generating simple customized pages for PICO-8 games.",
    links: [
      "https://seansleblanc.itch.io/pico-8-styler",
      "https://github.com/seleb/PICO-8-Styler",
      "/stuff/PICO-8-Styler",
    ],
  },
  {
    title: "#MURDERJAM2016",
    thumbnail: "thumbnails/MURDERJAM2016/thumbnail.gif",
    preview: "thumbnails/MURDERJAM2016/preview.gif",
    association: "#OJAM2016",
    date: "2016 June 26",
    tagline:
      "A game jam gone wrong, and it's up to your selective hearing to solve the mystery!",
    description: "",
    links: [
      "https://sweetheartsquad.itch.io/murderjam2016",
      "https://github.com/seleb/OJAM2016",
    ],
  },
  {
    title: "atopy",
    thumbnail: "thumbnails/atopy/thumbnail.png",
    preview: "thumbnails/atopy/preview.gif",
    association: "Personal Project",
    tags: ["software", "games", "PICO-8"],
    date: "2016 June 18",
    tagline: "try to fight it",
    description:
      "A viscerally challenging and challengingly visceral stealth combat game.",
    links: [
      "https://seansleblanc.itch.io/atopy",
      "https://github.com/seleb/atopy",
      "https://lexaloffle.com/bbs/?tid=3633",
    ],
  },
  {
    title: "Soda-Pop Sailin'",
    thumbnail: "thumbnails/Soda-Pop Sailin'/thumbnail.gif",
    preview: "thumbnails/Soda-Pop Sailin'/preview.gif",
    association: "#simplejam",
    tags: ["software", "games", "PICO-8"],
    date: "2016 June 10",
    tagline: "Save your crew from the carbonated seas!",
    description:
      "A zero-asset PICO-8 game. Everything including graphics and sound are generated through code.",
    links: [
      "https://seansleblanc.itch.io/soda-pop-sailin",
      "https://github.com/seleb/SimpleJam",
      "https://lexaloffle.com/bbs/?tid=3576",
    ],
  },
  {
    title: "JS Sprite Packer",
    thumbnail: "thumbnails/JS Sprite Packer/thumbnail.png",
    preview: "thumbnails/JS Sprite Packer/preview.png",
    association: "#toolboxjam",
    date: "2016 June 02",
    tagline:
      "A quick-and-dirty sprite packer made entirely with client-side JavaScript.",
    description: "",
    links: [
      "https://seansleblanc.itch.io/js-sprite-packer",
      "https://github.com/seleb/JS-Sprite-Packer",
    ],
  },
  {
    title: "Star Picker-Upper",
    thumbnail: "thumbnails/Star Picker-Upper/thumbnail.png",
    preview: "thumbnails/Star Picker-Upper/preview.gif",
    association: "#p8jam2",
    tags: ["software", "games", "PICO-8"],
    date: "2016 May 26",
    tagline: "A game about picking up stars!",
    description: "A simple game made with PICO-8.",
    links: [
      "https://seansleblanc.itch.io/star-picker-upper",
      "https://github.com/seleb/p8jam2",
      "https://lexaloffle.com/bbs/?tid=3432",
    ],
  },
  {
    title: "Deluge Suites",
    thumbnail: "thumbnails/Deluge Suites/thumbnail.png",
    preview: "thumbnails/Deluge Suites/preview.gif",
    association: "#CITYSIMJAM",
    tags: ["software", "games", "S-Tengine2"],
    date: "2016 May 15",
    tagline: "Can you keep your hotel afloat?",
    description:
      "A cheery little isometric game about managing a business during the end of the world.",
    links: [
      "https://sweetheartsquad.itch.io/deluge-suites",
      "https://github.com/seleb/CITYSIMJAM",
    ],
  },
  {
    title: "Purity",
    thumbnail: "thumbnails/Purity/thumbnail.png",
    preview: "thumbnails/Purity/preview.gif",
    association: "Ludum Dare 35",
    tags: ["software", "games", "S-Tengine2"],
    date: "2016 April 18",
    tagline: "Protect your fragile heart from the infectious impurities!",
    description:
      "A reverse bullet-hell game with a hyper-agressive aesthetic and a steep difficulty curve.",
    links: [
      "https://sweetheartsquad.itch.io/purity",
      "https://github.com/seleb/LD35",
      "http://ludumdare.com/compo/ludum-dare-35/?action=preview&uid=50235",
    ],
  },
  {
    title: "Drive Forever",
    thumbnail: "thumbnails/Drive Forever/thumbnail.png",
    preview: "thumbnails/Drive Forever/preview.gif",
    association: "#LOWREZJAM",
    date: "2016 April 17",
    tagline: "You're going to have to keep this up forever.",
    description: "",
    links: ["https://sweetheartsquad.itch.io/drive-forever"],
  },
  {
    title: "★ Creamie Buddies ★",
    thumbnail: "thumbnails/★ Creamie Buddies ★/thumbnail.gif",
    preview: "thumbnails/★ Creamie Buddies ★/preview.gif",
    association: "#LOWREZJAM",
    date: "2016 April 13",
    tagline: "Scoop Me Up!",
    description: "",
    links: ["https://sweetheartsquad.itch.io/creamie-buddies"],
  },
  {
    title: "Good Duel Game",
    thumbnail: "thumbnails/Good Duel Game/thumbnail.png",
    preview: "thumbnails/Good Duel Game/preview.gif",
    association: "#LOWREZJAM",
    date: "2016 April 06",
    tagline: "A good duel game",
    description: "",
    links: ["https://sweetheartsquad.itch.io/good-duel-game"],
  },
  {
    title: "Stone Cold Sexy",
    thumbnail: "thumbnails/Stone Cold Sexy/thumbnail.png",
    preview: "thumbnails/Stone Cold Sexy/preview.gif",
    association: "#LOWREZJAM",
    date: "2016 April 05",
    tagline: "pose 4 peeps",
    description: "",
    links: ["https://sweetheartsquad.itch.io/stone-cold-sexy"],
  },
  {
    title: "SODZEN",
    thumbnail: "thumbnails/SODZEN/thumbnail.png",
    preview: "thumbnails/SODZEN/preview.gif",
    association: "#LOWREZJAM2016",
    tags: ["software", "games", "S-Tengine2"],
    date: "2016 April 03",
    tagline: "A little pot of paradise.",
    description:
      'A 64 by 64 pixel zen experiment created for a game jam. See other entries I worked on <a target="_blank" href="/stuff/LOWREZJAM2016">here</a>.',
    links: [
      "https://sweetheartsquad.itch.io/sodzen",
      "https://github.com/seleb/LOWREZJAM",
      "/stuff/LOWREZJAM2016",
    ],
  },
  {
    title: "CODENAME: PAWN",
    thumbnail: "thumbnails/CODENAME PAWN/thumbnail.png",
    preview: "thumbnails/CODENAME PAWN/preview.gif",
    association: "Mini-Ludum Dare 66",
    tags: ["software", "games", "S-Tengine2"],
    date: "2016 April 01",
    tagline: "You have to kill the sleeper agents.",
    description:
      "A surveillance-themed RTS-lite. This is a game of patience and attention to detail.",
    links: [
      "https://sweetheartsquad.itch.io/codename-pawn",
      "https://github.com/seleb/MiniLD66",
    ],
  },
  {
    title: "Party, Darling?",
    thumbnail: "thumbnails/Party, Darling/thumbnail.gif",
    preview: "thumbnails/Party, Darling/preview.gif",
    association: "Carleton University",
    tags: ["software", "games", "S-Tengine2"],
    tagline:
      "A weird & abrasive sci-fi mystery adventure game from the SweetHeart Squad.",
    description:
      "A procedurally generated adventure game. This is my team's senior project from Carleton.",
    links: [
      "https://sweetheartsquad.itch.io/party-darling",
      "https://github.com/SweetheartSquad/Game",
    ],
    showcase: true,
    date: "2016 March 09",
  },
  {
    title: "Rip It! Grip It! Sip It!",
    thumbnail: "thumbnails/Rip It! Grip It! Sip It!/thumbnail.gif",
    preview: "thumbnails/Rip It! Grip It! Sip It!/preview.gif",
    association: "#GGJ2016",
    date: "2016 February 04",
    tagline:
      "The exorcising adventures of Father Skyler, punk priest extraordinaire.",
    description:
      "Rip, grip, and sip some demons out of their unwilling human hosts!",
    links: [
      "https://sweetheartsquad.itch.io/rip-it-grip-it-sip-it",
      "https://github.com/SweetheartSquad/GameJam2016",
    ],
  },
  {
    title: "Super Spaceship 64",
    thumbnail: "thumbnails/Super Spaceship 64/thumbnail.png",
    preview: "thumbnails/Super Spaceship 64/preview.png",
    association: "MiniLD64",
    tagline: "inspired by Starfox and Superman 64",
    date: "2016 January 25",
    description: "",
    links: ["https://sweetheartsquad.itch.io/super-spaceship-64"],
  },
  {
    title: "Llammigration (demo)",
    thumbnail: "thumbnails/Llammigration/thumbnail.png",
    preview: "thumbnails/Llammigration/preview.gif",
    association: "Carleton University",
    tagline: "Learning With Llama",
    description: "An unfinished educational game in the vein of Oregon Trail",
    date: "2015 December 21",
    links: ["https://sweetheartsquad.itch.io/llammigration"],
  },
  {
    title: "Go On",
    thumbnail: "thumbnails/Go On/thumbnail.png",
    preview: "thumbnails/Go On/preview.gif",
    association: "Ludum Dare 34",
    tags: ["software", "games", "S-Tengine2"],
    date: "2015 December 15",
    tagline: "A two-button game about growing up.",
    description:
      "Originally just a lighting experiment, this game was inspired by <em>Passage</em> and is awfully moody.",
    links: [
      "https://sweetheartsquad.itch.io/go-on",
      "https://github.com/seleb/LudumDare34",
      "http://ludumdare.com/compo/ludum-dare-34/?action=preview&uid=50235",
    ],
  },
  {
    title: "Taxi Quest 64",
    thumbnail: "thumbnails/Taxi Quest 64/thumbnail.png",
    preview: "thumbnails/Taxi Quest 64/preview.png",
    association: "#LD34",
    tagline: "A short experiment for Ludum Dare 34.",
    description: "A game about driving around a mercenary in your taxi.",
    date: "2015 December 15",
    links: ["https://sweetheartsquad.itch.io/taxi-quest-64"],
  },
  {
    title: "SweetBeats",
    thumbnail: "thumbnails/SweetBeats/thumbnail.png",
    preview: "thumbnails/SweetBeats/preview.png",
    association: "#procjam",
    date: "2015 November 15",
    tagline: "A simple procedural beat generator.",
    description: "",
    links: ["https://sweetheartsquad.itch.io/sweetbeats"],
  },
  {
    title: "StarBunny",
    thumbnail: "thumbnails/StarBunny/thumbnail.png",
    preview: "thumbnails/StarBunny/preview.gif",
    association: "Carleton University",
    date: "2015 October 18",
    tags: ["software", "music", "threejs"],
    tagline: "A WebGL audiovisual experience.",
    description:
      "Features the Stanford bunny and music by Retroman. Built with Three.js and the AudioContext API.",
    links: ["/stuff/webgl-starbunny"],
  },
  {
    title: "Dad, Don't Open Spyware!!!",
    thumbnail: "thumbnails/Dad, Don't Open Spyware!!!/thumbnail.png",
    preview: "thumbnails/Dad, Don't Open Spyware!!!/preview.png",
    association: "OJAM",
    date: "2015 July 03",
    tagline:
      "Lo-fi cyberspace meets horde-mode action for a lesson in parenting.",
    description:
      "This is a game of coordination. As a Mother/Son hacker team, you must press your special attack buttons at the same time to initiate powerful moves. Don't be a victim of bad data -- defeat waves of viruses and net nasties to save the day!",
    links: ["https://sweetheartsquad.itch.io/dad-dont-open-spyware"],
  },
  {
    title: "Hare's Hollow",
    thumbnail: "thumbnails/Hare's Hollow/thumbnail.png",
    preview: "thumbnails/Hare's Hollow/preview.png",
    association: "#wagchallenge",
    date: "2015 July 01",
    tagline: "A visual novel about funny animals, and the nature of Nature.",
    description:
      "An exciting visual novel for 3 of your 5 senses. Play as Fox and explore Hare's Hollow to discover the secret story of the animals. Originally developed in a custom C++ OpenGL engine, and later ported to WebGL.",
    links: [
      "https://sweetheartsquad.itch.io/hares-hollow",
      "https://github.com/SweetheartSquad/Hare-s-Hollow-html5",
      "https://github.com/SweetheartSquad/WAG-Challenge",
    ],
  },
  {
    title: "S-Tengine 2",
    thumbnail: "thumbnails/S-Tengine-2/thumbnail.png",
    preview: "thumbnails/S-Tengine-2/preview.gif",
    association: "Carleton University",
    date: "2014 July 20",
    tags: ["software", "tool", "S-Tengine2"],
    tagline:
      "The best game engine ever made by people who don't know how to make game engines.",
    description:
      "An open source OpenGL-based C++ game engine. Used to develop over a dozen indie freeware titles.",
    links: ["https://github.com/SweetheartSquad/S-Tengine2"],
  },
  {
    title: "3dSplineConnections",
    thumbnail: "thumbnails/Hair/thumbnail.png",
    preview: "thumbnails/Hair/preview.gif",
    association: "University of Ottawa",
    date: "2014 December 01",
    tags: ["software", "tool", "research"],
    tagline: "Hair modelling research.",
    description:
      "A Cinder-based 3D UI used to optimize data in an automated hair modelling pipeline.",
    links: [],
  },
  {
    title: "SPH",
    thumbnail: "thumbnails/SPH/thumbnail.png",
    preview: "thumbnails/SPH/preview.gif",
    association: "Carleton University",
    date: "2013 August 31",
    tags: ["software", "research"],
    tagline: "Smoothed Particle Hydrodynamics research",
    description:
      "Contributions to SPH system including plastic deformation model, optimizations using nVidia's CUDA platform, and Maya visualization tools.",
    links: [
      "https://link.springer.com/article/10.1007/s00371-014-0981-y",
      "https://link.springer.com/chapter/10.1007/978-981-287-134-3_10",
    ],
  },
];
