name: Deploy website on push

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  DISCORD_USERNAME: ${{ github.repository }}
  DISCORD_AVATAR: https://raw.githubusercontent.com/${{ github.repository }}/main/public/favicon-32x32.png

jobs:
  notify-start:
    runs-on: ubuntu-latest
    steps:
      - uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{ "color": 16426275, "title": "deploying...", "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }]'

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          local-dir: ./out/
          server-dir: ./public_html/

  notify-finished:
    if: ${{ success() || failure() }}
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: Ilshidur/action-discord@0.3.2
        if: ${{ needs.deploy.success() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{ "color": 2357925, "title": "deployed", "url": "https://seans.site" }]'
      - uses: Ilshidur/action-discord@0.3.2
        if: ${{ needs.deploy.failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{ "color": 16393080, "title": "failed", "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }]'
